/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ZidiumWebServiceFrontCategoryDto } from '../model/models';
import { ZidiumWebServiceFrontDictionariesCategoriesDtoCategoryListDto } from '../model/models';
import { ZidiumWebServiceFrontEditCategoryDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface DeleteRequestParams {
    id: number;
}

export interface AddRequestParams {
    zidiumWebServiceFrontEditCategoryDto?: ZidiumWebServiceFrontEditCategoryDto;
}

export interface GetAllRequestParams {
    search?: string;
    pageSize?: number;
    pageNumber?: number;
    sortDesc?: boolean;
}

export interface GetByIdRequestParams {
    id: number;
}

export interface NameExistsRequestParams {
    name: string;
    id?: number;
}

export interface UpdateRequestParams {
    id: number;
    zidiumWebServiceFrontEditCategoryDto?: ZidiumWebServiceFrontEditCategoryDto;
}


export interface CategoriesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    _delete(requestParameters: DeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    add(requestParameters: AddRequestParams, extraHttpRequestParams?: any): Observable<number>;

    /**
     * 
     * 
* @param requestParameters
     */
    getAll(requestParameters: GetAllRequestParams, extraHttpRequestParams?: any): Observable<ZidiumWebServiceFrontDictionariesCategoriesDtoCategoryListDto>;

    /**
     * 
     * 
* @param requestParameters
     */
    getById(requestParameters: GetByIdRequestParams, extraHttpRequestParams?: any): Observable<ZidiumWebServiceFrontCategoryDto>;

    /**
     * 
     * 
* @param requestParameters
     */
    nameExists(requestParameters: NameExistsRequestParams, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     * 
     * 
* @param requestParameters
     */
    update(requestParameters: UpdateRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
