/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ZidiumWebServiceFrontComponentHealthAtMomentDto } from '../model/models';
import { ZidiumWebServiceFrontComponentHealthDto } from '../model/models';
import { ZidiumWebServiceFrontComponentHealthHistoryItemDto } from '../model/models';
import { ZidiumWebServiceFrontComponentHealthReasonDto } from '../model/models';
import { ZidiumWebServiceFrontComponentStatusHistoryItemDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetHealthRequestParams {
    componentId: number;
    from?: string;
    to?: string;
    categoryId?: number;
}

export interface GetHealthAtMomentRequestParams {
    componentId: number;
    at?: string;
    categoryId?: number;
}

export interface GetHealthHistoryRequestParams {
    componentId: number;
    from?: string;
    to?: string;
    categoryId?: number;
    pageSize?: number;
    pageNumber?: number;
    sortDesc?: boolean;
}

export interface GetHealthReasonsRequestParams {
    componentId: number;
    at?: string;
    categoryId?: number;
}

export interface GetStatusHistoryRequestParams {
    componentId: number;
    from?: string;
    to?: string;
    categoryId?: number;
    pageSize?: number;
    pageNumber?: number;
    sortDesc?: boolean;
}


export interface ComponentHealthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Получение данных для детализации компонента, закладка Health
     * 
* @param requestParameters
     */
    getHealth(requestParameters: GetHealthRequestParams, extraHttpRequestParams?: any): Observable<ZidiumWebServiceFrontComponentHealthDto>;

    /**
     * Получение здоровья компонента на указанный момент времени
     * 
* @param requestParameters
     */
    getHealthAtMoment(requestParameters: GetHealthAtMomentRequestParams, extraHttpRequestParams?: any): Observable<ZidiumWebServiceFrontComponentHealthAtMomentDto>;

    /**
     * Получение истории здоровья компонента
     * 
* @param requestParameters
     */
    getHealthHistory(requestParameters: GetHealthHistoryRequestParams, extraHttpRequestParams?: any): Observable<Array<ZidiumWebServiceFrontComponentHealthHistoryItemDto>>;

    /**
     * Получение причин здоровья для компонента
     * 
* @param requestParameters
     */
    getHealthReasons(requestParameters: GetHealthReasonsRequestParams, extraHttpRequestParams?: any): Observable<Array<ZidiumWebServiceFrontComponentHealthReasonDto>>;

    /**
     * Получение истории статусов компонента
     * 
* @param requestParameters
     */
    getStatusHistory(requestParameters: GetStatusHistoryRequestParams, extraHttpRequestParams?: any): Observable<Array<ZidiumWebServiceFrontComponentStatusHistoryItemDto>>;

}
