/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ZidiumWebServiceFrontComponentChannelSubscriptionDto } from '../model/models';
import { ZidiumWebServiceFrontComponentTotalSubscriptionDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetForChannelRequestParams {
    componentId: number;
    channelId: number;
}

export interface GetTotalRequestParams {
    componentId: number;
}


export interface ComponentSubscriptionsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Получение подписок для компонента и канала
     * 
* @param requestParameters
     */
    getForChannel(requestParameters: GetForChannelRequestParams, extraHttpRequestParams?: any): Observable<ZidiumWebServiceFrontComponentChannelSubscriptionDto>;

    /**
     * Получение итоговых подписок для компонента
     * 
* @param requestParameters
     */
    getTotal(requestParameters: GetTotalRequestParams, extraHttpRequestParams?: any): Observable<Array<ZidiumWebServiceFrontComponentTotalSubscriptionDto>>;

}
