/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ZidiumWebServiceFrontComponentTreeItemExpandedDto } from '../model/models';
import { ZidiumWebServiceFrontComponentTreeItemPermissions } from '../model/models';
import { ZidiumWebServiceFrontComponentTreeResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetItemRequestParams {
    componentId: number;
    from?: string;
    to?: string;
    categoryId?: number;
}

export interface GetPermissionsRequestParams {
    componentId: number;
}

export interface GetTreeRequestParams {
    expandComponents?: Array<number>;
    componentId?: number;
    indicatorId?: number;
    from?: string;
    to?: string;
    categoryId?: number;
}


export interface ComponentTreeServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Раскрытие компонента в дереве
     * 
* @param requestParameters
     */
    getItem(requestParameters: GetItemRequestParams, extraHttpRequestParams?: any): Observable<ZidiumWebServiceFrontComponentTreeItemExpandedDto>;

    /**
     * Получение прав доступа к компоненту
     * 
* @param requestParameters
     */
    getPermissions(requestParameters: GetPermissionsRequestParams, extraHttpRequestParams?: any): Observable<ZidiumWebServiceFrontComponentTreeItemPermissions>;

    /**
     * Получение дерева компонентов
     * 
* @param requestParameters
     */
    getTree(requestParameters: GetTreeRequestParams, extraHttpRequestParams?: any): Observable<ZidiumWebServiceFrontComponentTreeResponseDto>;

}
