/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ZidiumWebServiceFrontComponentHealthFormulaItemDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetHealthFormulaRequestParams {
    componentId: number;
    at?: string;
    categoryId?: number;
}


export interface ComponentHealthFormulaServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Получение формулы здоровья для компонента
     * 
* @param requestParameters
     */
    getHealthFormula(requestParameters: GetHealthFormulaRequestParams, extraHttpRequestParams?: any): Observable<Array<ZidiumWebServiceFrontComponentHealthFormulaItemDto>>;

}
