/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ZidiumWebServiceFrontComponentSettingsDto } from '../model/models';
import { ZidiumWebServiceFrontComponentSettingsEditableDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface DeleteRequestParams {
    componentId: number;
}

export interface AddRequestParams {
    componentId: number;
    zidiumWebServiceFrontComponentSettingsEditableDto?: ZidiumWebServiceFrontComponentSettingsEditableDto;
}

export interface DisableRequestParams {
    componentId: number;
}

export interface EnableRequestParams {
    componentId: number;
}

export interface GetRequestParams {
    componentId: number;
}

export interface SystemNameExistsRequestParams {
    componentId: number;
    systemName: string;
    childComponentId?: number;
}

export interface UpdateRequestParams {
    componentId: number;
    zidiumWebServiceFrontComponentSettingsEditableDto?: ZidiumWebServiceFrontComponentSettingsEditableDto;
}


export interface ComponentSettingsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Удаление компонента
     * 
* @param requestParameters
     */
    _delete(requestParameters: DeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Добавление компонента
     * 
* @param requestParameters
     */
    add(requestParameters: AddRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Отключение компонента
     * 
* @param requestParameters
     */
    disable(requestParameters: DisableRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Включение компонента
     * 
* @param requestParameters
     */
    enable(requestParameters: EnableRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Получение настроек компонента
     * 
* @param requestParameters
     */
    get(requestParameters: GetRequestParams, extraHttpRequestParams?: any): Observable<ZidiumWebServiceFrontComponentSettingsDto>;

    /**
     * Проверка существования дочернего компонента с указанным системным названием
     * 
* @param requestParameters
     */
    systemNameExists(requestParameters: SystemNameExistsRequestParams, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     * Изменение настроек компонента
     * 
* @param requestParameters
     */
    update(requestParameters: UpdateRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
