/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ZidiumWebServiceFrontComponentHeaderDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetHeaderRequestParams {
    componentId: number;
}


export interface ComponentHeaderServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Получение общей информации о компоненте для шапки детализации
     * 
* @param requestParameters
     */
    getHeader(requestParameters: GetHeaderRequestParams, extraHttpRequestParams?: any): Observable<ZidiumWebServiceFrontComponentHeaderDto>;

}
