/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { SetComponentLinkRequestDto } from '../model/models';
import { ZidiumWebServiceFrontComponentLinksDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface DeleteLinkRequestParams {
    componentId: number;
    sourceComponentId: number;
}

export interface GetLinksRequestParams {
    componentId: number;
}

export interface SetLinkRequestParams {
    componentId: number;
    setComponentLinkRequestDto?: SetComponentLinkRequestDto;
}


export interface ComponentLinksServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Удаление связи влияния
     * 
* @param requestParameters
     */
    deleteLink(requestParameters: DeleteLinkRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Получение ссылок компонента
     * 
* @param requestParameters
     */
    getLinks(requestParameters: GetLinksRequestParams, extraHttpRequestParams?: any): Observable<ZidiumWebServiceFrontComponentLinksDto>;

    /**
     * Установка связи влияния
     * 
* @param requestParameters
     */
    setLink(requestParameters: SetLinkRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
