/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ZidiumWebServiceFrontComponentSelectorDto } from '../model/models';
import { ZidiumWebServiceFrontSelectorDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetFullNameRequestParams {
    componentId: number;
}

export interface GetItemRequestParams {
    componentId: number;
    search?: string;
}

export interface GetTreeRequestParams {
    componentId?: number;
    search?: string;
}


export interface SelectorsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Получение списка для выбора категории
     * 
*/
    getCategories(extraHttpRequestParams?: any): Observable<Array<ZidiumWebServiceFrontSelectorDto>>;

    /**
     * Получение списка для выбора типа компонента
     * 
*/
    getComponentTypes(extraHttpRequestParams?: any): Observable<Array<ZidiumWebServiceFrontSelectorDto>>;

    /**
     * Получение полного имени компонента
     * 
* @param requestParameters
     */
    getFullName(requestParameters: GetFullNameRequestParams, extraHttpRequestParams?: any): Observable<Array<string>>;

    /**
     * Раскрытие компонента в дереве
     * 
* @param requestParameters
     */
    getItem(requestParameters: GetItemRequestParams, extraHttpRequestParams?: any): Observable<Array<ZidiumWebServiceFrontComponentSelectorDto>>;

    /**
     * Получение дерева компонентов для выбора
     * 
* @param requestParameters
     */
    getTree(requestParameters: GetTreeRequestParams, extraHttpRequestParams?: any): Observable<Array<ZidiumWebServiceFrontComponentSelectorDto>>;

}
