/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ZidiumWebServiceFrontDefaultSubscriptionDto } from '../model/models';
import { ZidiumWebServiceFrontDeleteDefaultSubscriptionDto } from '../model/models';
import { ZidiumWebServiceFrontDeleteObjectSubscriptionDto } from '../model/models';
import { ZidiumWebServiceFrontObjectSubscriptionDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface DeleteDefaultRequestParams {
    zidiumWebServiceFrontDeleteDefaultSubscriptionDto?: ZidiumWebServiceFrontDeleteDefaultSubscriptionDto;
}

export interface DeleteForObjectRequestParams {
    zidiumWebServiceFrontDeleteObjectSubscriptionDto?: ZidiumWebServiceFrontDeleteObjectSubscriptionDto;
}

export interface SaveDefaultRequestParams {
    zidiumWebServiceFrontDefaultSubscriptionDto?: ZidiumWebServiceFrontDefaultSubscriptionDto;
}

export interface SaveForObjectRequestParams {
    zidiumWebServiceFrontObjectSubscriptionDto?: ZidiumWebServiceFrontObjectSubscriptionDto;
}


export interface SubscriptionsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Удаление подписки по умолчанию
     * 
* @param requestParameters
     */
    deleteDefault(requestParameters: DeleteDefaultRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Удаление подписки для объекта
     * 
* @param requestParameters
     */
    deleteForObject(requestParameters: DeleteForObjectRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Сохранение подписки по умолчанию
     * 
* @param requestParameters
     */
    saveDefault(requestParameters: SaveDefaultRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Сохранение подписки для объекта
     * 
* @param requestParameters
     */
    saveForObject(requestParameters: SaveForObjectRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
