/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ZidiumWebServiceFrontComponentLinkDto { 
    componentId: number;
    displayName: string;
    fullName: Array<string>;
    weight: number;
}

