/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontComponentTreeIndicatorDto } from './zidiumWebServiceFrontComponentTreeIndicatorDto.model';
import { ZidiumWebServiceFrontComponentTreeEventsDto } from './zidiumWebServiceFrontComponentTreeEventsDto.model';
import { ZidiumWebServiceFrontComponentTreeItemDto } from './zidiumWebServiceFrontComponentTreeItemDto.model';


export interface ZidiumWebServiceFrontComponentTreeItemExpandedDto { 
    readonly childComponents: Array<ZidiumWebServiceFrontComponentTreeItemDto>;
    readonly indicators: Array<ZidiumWebServiceFrontComponentTreeIndicatorDto>;
    events?: ZidiumWebServiceFrontComponentTreeEventsDto;
}

