/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontUserContactItemDto } from './zidiumWebServiceFrontUserContactItemDto.model';
import { ZidiumWebServiceFrontUserInGroupItemDto } from './zidiumWebServiceFrontUserInGroupItemDto.model';


export interface ZidiumWebServiceFrontUserDto { 
    id: number;
    canEdit: boolean;
    canDelete: boolean;
    name: string;
    displayName: string;
    timeZoneOffset: string;
    timeZoneName: string;
    contacts: Array<ZidiumWebServiceFrontUserContactItemDto>;
    groups: Array<ZidiumWebServiceFrontUserInGroupItemDto>;
    canEditName: boolean;
    canEditGroups: boolean;
}

