/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontHealthAndStatusDto } from './zidiumWebServiceFrontHealthAndStatusDto.model';
import { ZidiumWebServiceFrontComponentStatusHistoryItemDto } from './zidiumWebServiceFrontComponentStatusHistoryItemDto.model';


export interface ZidiumWebServiceFrontComponentHealthDto { 
    healthAndStatus?: ZidiumWebServiceFrontHealthAndStatusDto;
    items: Array<ZidiumWebServiceFrontComponentStatusHistoryItemDto>;
}

