/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IndicatorDataType } from './indicatorDataType.model';


export interface ZidiumWebServiceFrontEditPeriodicCheckTypeDto { 
    name: string;
    indicatorDataType: IndicatorDataType;
    url?: string | null;
}
export namespace ZidiumWebServiceFrontEditPeriodicCheckTypeDto {
}


