/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontRoleCommonPermissionItem } from './zidiumWebServiceFrontRoleCommonPermissionItem.model';
import { ZidiumWebServiceFrontRolePermissionByComponentItem } from './zidiumWebServiceFrontRolePermissionByComponentItem.model';


export interface ZidiumWebServiceFrontRoleDto { 
    id: number;
    canEdit: boolean;
    canDelete: boolean;
    name: string;
    commonPermissions: Array<ZidiumWebServiceFrontRoleCommonPermissionItem>;
    permissionsByComponent: Array<ZidiumWebServiceFrontRolePermissionByComponentItem>;
}

