/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IndicatorDataType } from './indicatorDataType.model';
import { ZidiumCoreApiStatus } from './zidiumCoreApiStatus.model';


export interface ZidiumWebServiceFrontComponentTreeIndicatorDto { 
    id: number;
    displayName: string;
    isEnabled: boolean;
    dataType: IndicatorDataType;
    status: ZidiumCoreApiStatus;
    value?: any | null;
    message?: string | null;
}
export namespace ZidiumWebServiceFrontComponentTreeIndicatorDto {
}


