/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontComponentTreeItemDto } from './zidiumWebServiceFrontComponentTreeItemDto.model';


export interface ZidiumWebServiceFrontComponentTreeResponseDto { 
    items: Array<ZidiumWebServiceFrontComponentTreeItemDto>;
}

