/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumCoreApiStatus } from './zidiumCoreApiStatus.model';


export interface ZidiumWebServiceFrontComponentTreeEventsDto { 
    status: ZidiumCoreApiStatus;
}
export namespace ZidiumWebServiceFrontComponentTreeEventsDto {
}


